version: "3"

services:
  job-portal:
    container_name: my-jobPortal-container
    image: job-portal
    ports: 
      - "8082:8082"
    build: . 
    env_file:
      - .app.env
      - .db.env
      - .redis.env
      - .privatepublic.env
    depends_on:
      - postgres
      - redis
    restart: always 
  redis:
    container_name: my-redis-container
    image: redis
    ports:
      - "6379:6379"
  postgres:
    container_name: my-postgres-container
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSRGRES_DB=postgres