version: "3"

services:
  job-portal:
    container_name: job-portal
    image: job-portal
    ports: 
      - "8082:8082"
    build: . 
    env_file:
      - .env
      - .app.env
    depends_on:
      - postgres
    restart: always  
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSRGRES_DB=postgres